### PR TITLE
Augmenting `FITS.readHeader1` with the capability of dealing with long, continuing strings

### PR DESCRIPTION
**Pull request by EastEriq**
And solving a few bugs in it related to the presence of slashes in strings (e.g. in pathnames) and their misinterpretation as separators of the comment field (which is not necessarily found at column 32).

Discussion in issues #394 and #395.  Support of #389 is probably not necessary, so at the time I didn't implement it.

I've done some testing of it, but since reading FITS is much too important, someone should vet the pull.

My test:
```
AI=AstroImage();

AI.Image=rand(3,3);

% add some normal and some exotic keys to the header
AI.HeaderData.insertKey({...
        'ONE',1,'a number';...
        'ALONGLONGNUMBER',2,'another number';...
        'ALONGLONGSTRING','this may be more interesting','figure what';...
        'THREE','a very very, but really a lot, and again, and more, and more and longer string',...
                'even with a comment';...
        'TWELVE','Like the previous, a very very, but really a lot, and again, and more, and more and longer string, but sooooo long that it goes on for several lines',...
                'even with a comment';...
        'ELEVEN',11,' still a number';...
        'PRAVDA',true,'logical, no? but here we could argue, forever, because comments are autoreferential';...
        'FOUR','a /very very/ but really a lot/ and again, and more/ and more and longer string',...
                'a rhyme ''/'' with many slashes/ so it is also/ pretty long';...
        });

testfile='/tmp/Test.fits';

AI.write1(testfile,'Overwrite',true);

AI2=AstroImage(testfile);

AI2.HeaderData.Data
```

### CODE REVIEW

**Comment by agioffe** [comment]
I have tested it with several types of long and strange data structures full of special symbols, but found no bugs. Thus, I cannot see any reasons not to merge it. Just one comment: when saving to a FITS file, the value of a keyword is correctly placed into CONTINUE lines however long it is, but the comment is cut to some limiting length (47 symbols? -- why such a number?), and not recovered when we read it again from this file (so not kept in full anywhere inside the FITS).

**Comment by EastEriq** [comment]
>when saving to a FITS file, the value of a keyword is correctly placed into CONTINUE lines however long it is, but the comment is cut to some limiting length (47 symbols? -- why such a number?), and not recovered when we read it again from this file (so not kept in full anywhere inside the FITS).

I'm aware of that, as for readHeader1 it was my lack of diligence in coding also the case of lines continuing the comment field; I implemented only the continuation of the value. Eran says that we can by all means skip it, but if anyone cares for that I can do an effort. As for writing, I think that `FITS.write` already does it, but anyway writing was not my scope.

>I have tested it with several types of long and strange data structures full of special symbols, but found no bugs.

Thanks for checking. If you put together some easy and exotic case, would you consider to add it to the unit test?

**Comment by agioffe** [comment]
I do agree with Eran, that it is not that important to keep long comment fields, it was just a note.
As a short example with special symbols we may add to the unitTest something like
```
AI.HeaderData.insertKey({'SymKey','sys\\tem?\&^M^V                   loong(((','with \\6& $ #strange sym)bols('})
```

**Comment by EastEriq** [comment]
> ```
> AI.HeaderData.insertKey({'SymKey','sys\\tem?\&^M^V                                                     loong(((','with \\6& $ #strange sym)bols('})
> ```
Good catch, this does NOT pass the unit test because of the 53 spaces which are trimmed to one. Having a look into it, though I think it might be quite a corner case that we could leave unsolved. In other cases trimming the strings is desirable.

**Comment by EastEriq** [comment]
Your last catch fixed by [81271be](https://github.com/EranOfek/AstroPack/pull/397/commits/81271be4a5f990bebc40b301f99763549e41a548). I overlooked that `strcat`, differently than simple array concatenation, *does* trim strings.

With that and as discussed with Sasha, I do the merge.

**Pull request merged**
